cd "C:\Users\cynthist\Documents\GitHub\AZ-900T0x-MicrosoftAzureFundamentals\Instructions\Walkthroughs"
pandoc "01-create a virtual machine.md" --output "c:\users\cynthist\documents\github\releases\01-Create a virtual machine.docx"
pandoc "02-Deploy Azure Container Instances.md" --output "c:\users\cynthist\documents\github\releases\02-Deploy Azure Container Instances.docx" 
pandoc "03-Create a virtual network.md" --output "c:\users\cynthist\documents\github\releases\03-Create a virtual network.docx" 
pandoc "04-Create Blob storage.md" --output "c:\users\cynthist\documents\github\releases\04-Create Blob storage.docx"
pandoc "05-Create a SQL database.md" --output "c:\users\cynthist\documents\github\releases\05-Create a SQL database.docx"
pandoc "06-Implement the Azure IoT Hub.md" --output "c:\users\cynthist\documents\github\releases\06-Implement the Azure IoT Hub.docx"
pandoc "07-Implement Azure Functions.md" --output "c:\users\cynthist\documents\github\releases\07-Implement Azure Functions.docx"
pandoc "08-Create a Web App.md" --output "c:\users\cynthist\documents\github\releases\08-Create a Web App.docx"
pandoc "09-Create a VM with a Template.md" --output "c:\users\cynthist\documents\github\releases\09-Create a VM with a Template.docx"
pandoc "10-Create a VM with PowerShell.md" --output "c:\users\cynthist\documents\github\releases\10-Create a VM with PowerShell.docx"
pandoc "12-Secure network traffic.md" --output "c:\users\cynthist\documents\github\releases\12-Secure network traffic.docx"
pandoc "13-Implement Azure Key Vault.md" --output "c:\users\cynthist\documents\github\releases\13-Implement Azure Key Vault.docx"
pandoc "14-Create an Azure Policy.md" --output "c:\users\cynthist\documents\github\releases\14-Create an Azure Policy.docx"
pandoc "15-Manage access with RBAC.md" --output "c:\users\cynthist\documents\github\releases\15-Manage access with RBAC.docx"
pandoc "16-Manage resource locks.md" --output "c:\users\cynthist\documents\github\releases\16-Manage resource locks.docx"
pandoc "17-Implement resource tagging.md" --output "c:\users\cynthist\documents\github\releases\17-Implement resource tagging.docx"
pandoc "18-Explore the Trust Center.md" --output "c:\users\cynthist\documents\github\releases\18-Explore the Trust Center.docx"
pandoc "19-Use the Azure Pricing Calculator.md" --output "c:\users\cynthist\documents\github\releases\19-Use the Azure Pricing Calculator.docx"
pandoc "20-Use the Azure TCO Calculator.md" --output "c:\users\cynthist\documents\github\releases\20-Use the Azure TCO Calculator.docx"
pandoc "21-Open a Support Request.md" --output "c:\users\cynthist\documents\github\releases\21-Open a Support Request.docx"
pandoc "22-Calculate Composite SLAs.md" --output "c:\users\cynthist\documents\github\releases\22-Calculate Composite SLAs.docx"
pandoc "23-Access Azure Preview features.md" --output "c:\users\cynthist\documents\github\releases\23-Access Azure Preview features.docx"